#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Domotica.Resource", IsApplication=true)]

namespace Domotica
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_media_play = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_media_stop = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070018
			public const int RadioGroup = 2131165208;
			
			// aapt resource value: 0x7f07002a
			public const int abort = 2131165226;
			
			// aapt resource value: 0x7f070015
			public const int buttonAllOff = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int buttonAllOn = 2131165206;
			
			// aapt resource value: 0x7f070008
			public const int buttonConnect = 2131165192;
			
			// aapt resource value: 0x7f070023
			public const int buttonStartMusic = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int buttonStartMusic2 = 2131165222;
			
			// aapt resource value: 0x7f07001d
			public const int buttonStartTimer = 2131165213;
			
			// aapt resource value: 0x7f070024
			public const int buttonStopMusic = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int buttonStopMusic2 = 2131165223;
			
			// aapt resource value: 0x7f070007
			public const int editTextIPAddress = 2131165191;
			
			// aapt resource value: 0x7f07001f
			public const int editTextMinutes = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int editTextSeconds = 2131165214;
			
			// aapt resource value: 0x7f070029
			public const int exit = 2131165225;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070019
			public const int radioButton1 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int radioButton2 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int radioButton3 = 2131165211;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int switch1 = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int switch2 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int switch3 = 2131165204;
			
			// aapt resource value: 0x7f070021
			public const int switch4 = 2131165217;
			
			// aapt resource value: 0x7f07000a
			public const int switchLightSensor = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int switchTempSensor = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int textView1 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int textView2 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int textView3 = 2131165203;
			
			// aapt resource value: 0x7f070020
			public const int textView4 = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int textView5 = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int textView6 = 2131165221;
			
			// aapt resource value: 0x7f070006
			public const int textViewIPAddress = 2131165190;
			
			// aapt resource value: 0x7f070017
			public const int textViewRadioBtn = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int textViewSensor = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int textViewSensorValue = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int textViewServer = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textViewServerConnect = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int textViewTempSensor = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int textViewTempValue = 2131165198;
			
			// aapt resource value: 0x7f07001c
			public const int textViewTime = 2131165212;
			
			// aapt resource value: 0x7f070002
			public const int textViewTimerState = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textViewTimerStateValue = 2131165187;
			
			// aapt resource value: 0x7f070028
			public const int theme = 2131165224;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050011
			public const int abort = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int application_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int arduino_server_connect = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int arduino_server_text = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int button_connect_text = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int debug_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int edit_text_minutes = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int edit_text_seconds = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int exit = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int ip_address_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ip_address_value = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ip_port_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ip_port_value = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int sensor_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int sensor_value = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int temp_value = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int timer_state_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int timer_state_value = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
